version: '3.8'

services:
  # Pythonバックエンド
  python_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: paper_summary_backend
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    networks:
      - paper_summary_network
    restart: unless-stopped

  # Node.jsフロントエンド
  nodejs_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: paper_summary_frontend
    environment:
      REACT_APP_API_URL: http://localhost:8000
      NODE_ENV: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - python_backend
    networks:
      - paper_summary_network
    restart: unless-stopped


networks:
  paper_summary_network:
    driver: bridge